"""Unit tests for ``math_tools.otg.calculator_target.TargetCalculator``.

See ``.claude/specs/otg.md`` §Internal fidelity requirement 3 and
``.claude/action-plan/40-otg-calculator-target.md``'s TDD steps (a)-(e).
Cases (a)-(c) reuse chunk 38's rest-to-rest ``PositionThirdOrderStep1``
boundary conditions (``v_max=2, a_max=1, j_max=1``, ``pd/v_max +
v_max/a_max + a_max/j_max`` as the closed-form optimal duration) scaled to
different target distances, composed through the full ``calculate()`` path
rather than the bare step solver.

**Chunk 56 additions (post-audit findings E-4, E-5, E-6).** The classes
below ``TestUnsolvableSynchronizationReturnsErrorNotRaise`` close three
coverage gaps identified by the post-audit (``.claude/action-plan/
56-test-closure-otg-oracles.md``):

- ``TestMultiDofCorpusReachesStep2`` (E-4): the entire 1,784-case
  classification corpus is 1-DOF, which takes the dedicated fast path at
  ``calculator_target.py:553`` and never invokes
  ``PositionThirdOrderStep2.get_profile``. ``tests/otg/data/
  successful_trajectories_multi_dof.json`` (generated by
  ``tests/otg/data/generate_multi_dof_corpus.py``, fixed seed) combines
  1-DOF corpus cases into 2/3/4-DOF cases under the default ``TIME``
  synchronization, which is exactly what forces the non-limiting DOFs
  through Step2.
- ``TestPhaseSynchronization*`` (E-5): drives ``Synchronization.PHASE``
  through ``calculate()`` for real, both when the boundary conditions are
  collinear (phase-sync succeeds without a Step2 solve) and when they are
  not (falls back to per-DOF ``TIME`` synchronization, i.e. Step2).
- ``TestDiscreteDuration``, ``TestMinimumDuration``,
  ``TestTimeIfNecessarySynchronization``, ``TestVelocityControlInterface``
  (E-6): each drives one previously-0%-covered ``calculate()`` path
  end-to-end -- ``DurationDiscretization.DISCRETE``,
  ``InputParameter.minimum_duration``,
  ``Synchronization.TIME_IF_NECESSARY`` (both its "not necessary" early
  exit and its "necessary" Step2 fallthrough), and
  ``ControlInterface.VELOCITY``.
"""

import json
import math
import unittest
from pathlib import Path
from unittest.mock import patch

import math_tools.otg.steps.position_third_order_step2 as step2_module
from math_tools.otg.block import Interval
from math_tools.otg.calculator_target import TargetCalculator
from math_tools.otg.enums import ControlInterface, DurationDiscretization, Result, Synchronization
from math_tools.otg.input_parameter import InputParameter
from math_tools.otg.otg import Otg
from math_tools.otg.output_parameter import OutputParameter
from math_tools.otg.steps.position_third_order_step2 import PositionThirdOrderStep2
from math_tools.otg.trajectory import Trajectory

_DATA_DIR = Path(__file__).parent / "data"

_V_MAX = 2.0
_A_MAX = 1.0
_J_MAX = 1.0


def _rest_to_rest_optimal_duration(pd: float) -> float:
    """Closed-form time-optimal duration for a rest-to-rest move of
    distance ``pd`` under ``_V_MAX``/``_A_MAX``/``_J_MAX`` (matches chunk
    38's ``expected_total = pf / v_max + v_max / a_max + a_max / j_max``,
    valid whenever the move is long enough to saturate both limits)."""
    return pd / _V_MAX + _V_MAX / _A_MAX + _A_MAX / _J_MAX


def _make_position_input(dofs: int, targets: list[float]) -> InputParameter:
    inp = InputParameter(dofs)
    inp.target_position = list(targets)
    inp.max_velocity = [_V_MAX] * dofs
    inp.min_velocity = [-_V_MAX] * dofs
    inp.max_acceleration = [_A_MAX] * dofs
    inp.min_acceleration = [-_A_MAX] * dofs
    inp.max_jerk = [_J_MAX] * dofs
    return inp


class TestSingleDofMatchesStep1AnalyticDuration(unittest.TestCase):
    """(a) 1-DOF position case reproduces chunk 38's analytic duration
    through the full ``calculate()`` path (the 1-DOF shortcut branch)."""

    def test_matches_chunk_38_long_move_duration_and_segments(self) -> None:
        dofs = 1
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0])

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        expected_duration = _rest_to_rest_optimal_duration(10.0)
        self.assertAlmostEqual(trajectory.duration, expected_duration, delta=1e-9)
        self.assertAlmostEqual(trajectory.cumulative_times[0], expected_duration, delta=1e-9)

        expected_t = [1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0]
        profile = trajectory.profiles[0][0]
        for i, expected in enumerate(expected_t):
            self.assertAlmostEqual(profile.t[i], expected, delta=1e-9, msg=f"t[{i}]")
        self.assertAlmostEqual(profile.p[-1], 10.0, delta=1e-8)


class TestThreeDofTimeSynchronization(unittest.TestCase):
    """(b) 3-DOF TIME sync -- every DOF reports the same trajectory
    duration, equal to the slowest DOF's own optimal duration."""

    def test_all_dofs_reach_the_slowest_dofs_optimal_duration(self) -> None:
        dofs = 3
        calc = TargetCalculator(dofs)
        targets = [10.0, 5.0, 2.0]
        inp = _make_position_input(dofs, targets)
        inp.synchronization = Synchronization.TIME

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        expected_duration = _rest_to_rest_optimal_duration(max(targets))
        self.assertAlmostEqual(trajectory.duration, expected_duration, delta=1e-9)

        for dof in range(dofs):
            profile = trajectory.profiles[0][dof]
            total = profile.t_sum[-1] + profile.brake.duration + profile.accel.duration
            self.assertAlmostEqual(total, expected_duration, delta=1e-8, msg=f"dof {dof}")
            self.assertAlmostEqual(profile.p[-1], targets[dof], delta=1e-6, msg=f"dof {dof}")


class TestThreeDofNoneSynchronization(unittest.TestCase):
    """(c) NONE sync -- per-DOF durations equal their independent optima
    (not stretched to the slowest DOF)."""

    def test_each_dof_keeps_its_own_optimal_duration(self) -> None:
        dofs = 3
        calc = TargetCalculator(dofs)
        targets = [10.0, 5.0, 2.0]
        inp = _make_position_input(dofs, targets)
        inp.synchronization = Synchronization.NONE

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)

        for dof in range(dofs):
            profile = trajectory.profiles[0][dof]
            total = profile.t_sum[-1] + profile.brake.duration + profile.accel.duration
            own_optimum = trajectory.independent_min_durations[dof]
            self.assertAlmostEqual(total, own_optimum, delta=1e-8, msg=f"dof {dof}")
            self.assertAlmostEqual(profile.p[-1], targets[dof], delta=1e-6, msg=f"dof {dof}")

        # Distinct targets (10/5/2) under identical limits must give
        # genuinely distinct independent optima -- otherwise this test
        # can't distinguish NONE sync from TIME sync.
        durations = trajectory.independent_min_durations
        self.assertGreater(durations[0], durations[1])
        self.assertGreater(durations[1], durations[2])

        # The trajectory's own bookkeeping duration is still the max
        # (slowest DOF), used for e.g. FINISHED detection by a driver.
        self.assertAlmostEqual(trajectory.duration, max(durations), delta=1e-9)


class TestDisabledDofStaysAtCurrentState(unittest.TestCase):
    """(d) an ``enabled=False`` DOF stays at its current state."""

    def test_disabled_dof_profile_holds_current_state(self) -> None:
        dofs = 2
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0, 99.0])  # dof1's target is irrelevant (disabled).
        inp.current_position = [0.0, 3.0]
        inp.current_velocity = [0.0, 0.5]
        inp.current_acceleration = [0.0, 0.1]
        inp.enabled = [True, False]

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)

        disabled_profile = trajectory.profiles[0][1]
        self.assertAlmostEqual(disabled_profile.p[-1], 3.0, delta=1e-12)
        self.assertAlmostEqual(disabled_profile.v[-1], 0.5, delta=1e-12)
        self.assertAlmostEqual(disabled_profile.a[-1], 0.1, delta=1e-12)
        self.assertAlmostEqual(disabled_profile.t_sum[-1], 0.0, delta=1e-12)

        # The enabled DOF must still solve normally.
        enabled_profile = trajectory.profiles[0][0]
        self.assertAlmostEqual(enabled_profile.p[-1], 10.0, delta=1e-6)


class TestTrivialProfileUsesFixedLengthArrays(unittest.TestCase):
    """(f) chunk 45 / post-audit finding E-2: the trivial "already at
    target" branch must produce the same fixed-length ``Profile`` arrays
    (``a``/``v``/``p`` length 8, ``t``/``t_sum``/``j`` length 7) as every
    other path, per ``.claude/specs/otg.md`` §Internal fidelity requirement
    1 -- not the 7-element form that made ``p.p[7]`` raise ``IndexError``.
    """

    def test_trivial_target_profile_arrays_are_fixed_length(self) -> None:
        dofs = 1
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [0.0])  # current_position defaults to 0.0 -> trivial.

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        profile = trajectory.profiles[0][0]
        self.assertEqual(len(profile.p), 8)
        self.assertEqual(len(profile.v), 8)
        self.assertEqual(len(profile.a), 8)
        self.assertEqual(len(profile.t), 7)
        self.assertEqual(len(profile.t_sum), 7)
        self.assertEqual(len(profile.j), 7)


class TestTrivialProfilePositionExtrema(unittest.TestCase):
    """(g) a trajectory parked at a non-zero position (trivial branch)
    must report that position as both min and max extrema, not ``0.0`` --
    requires ``p.pf`` to be set in the trivial branch."""

    def test_parked_trajectory_extrema_report_parked_position(self) -> None:
        dofs = 1
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [5.0])
        inp.current_position = [5.0]  # already at target -> trivial branch.

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        extrema = trajectory.position_extrema()
        self.assertAlmostEqual(extrema[0].min, 5.0, delta=1e-12)
        self.assertAlmostEqual(extrema[0].max, 5.0, delta=1e-12)


class TestUnsolvableSynchronizationReturnsErrorNotRaise(unittest.TestCase):
    """(e) an unsolvable synchronization input returns
    ``ERROR_SYNCHRONIZATION_CALCULATION`` rather than raising.

    ``TargetCalculator._synchronize``'s search is provably complete for any
    ``Block`` state actually produced by a successful Step1 call: a DOF's
    own ``t_min`` is never self-blocked at its own boundary, and neither is
    an ``Interval``'s own ``right`` edge (``Interval.is_blocked`` excludes
    both endpoints). Reaching "no candidate found" through a *naturally*
    Step1-derived ``InputParameter`` would require an adversarial multi-DOF
    interval coincidence that is impractical to hand-derive, so this is
    exercised two ways instead: directly, with a hand-built ``Block`` state
    proven (by construction, see the docstring below) to block every finite
    candidate; and through ``calculate()`` itself, with ``_synchronize``
    forced to fail via ``unittest.mock.patch.object`` to confirm the error
    propagates to the ``Result`` code without an exception.
    """

    def test_synchronize_returns_false_without_raising_when_all_candidates_blocked(self) -> None:
        calc = TargetCalculator(2)
        calc._inp_per_dof_synchronization = [Synchronization.TIME, Synchronization.TIME]

        # dof0: reachable only at t == 1.0 exactly (blocked for every t > 1.0
        # via an interval with an infinite right edge).
        calc._blocks[0].t_min = 1.0
        calc._blocks[0].a = Interval(1.0, math.inf)

        # dof1: its own t_min floor (2.0) blocks dof0's only escape point
        # (t == 1.0 < 2.0 == dof1.t_min -> Block.is_blocked(1.0) is True for
        # dof1), and dof1 contributes no interval of its own beyond that.
        calc._blocks[1].t_min = 2.0

        trajectory = Trajectory(2)
        found, _t_sync, _limiting_dof = calc._synchronize(
            None, trajectory.profiles[0], discrete_duration=False, delta_time=0.001
        )

        self.assertFalse(found)

    def test_calculate_propagates_synchronization_failure_without_raising(self) -> None:
        dofs = 2
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0, 5.0])

        trajectory = Trajectory(dofs)
        with patch.object(TargetCalculator, "_synchronize", return_value=(False, 0.0, None)):
            result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.ERROR_SYNCHRONIZATION_CALCULATION)


class TestMultiDofCorpusReachesStep2(unittest.TestCase):
    """Post-audit E-4: the 1-DOF classification corpus never reaches
    ``PositionThirdOrderStep2`` (the 1-DOF fast path at
    ``calculator_target.py:553`` copies the Step1 extremal profile
    directly). ``successful_trajectories_multi_dof.json`` (2/3/4-DOF,
    default ``TIME`` sync) is generated specifically to force the
    non-limiting DOFs through Step2 -- verified here by measuring the
    invocation count directly, not assuming reach from case shape alone."""

    def test_all_cases_succeed_and_step2_is_invoked(self) -> None:
        with (_DATA_DIR / "successful_trajectories_multi_dof.json").open() as f:
            cases = json.load(f)
        self.assertGreater(len(cases), 0, "successful_trajectories_multi_dof.json is empty")

        original_get_profile = step2_module.PositionThirdOrderStep2.get_profile
        invocation_count = 0

        def counting_get_profile(step2_self: PositionThirdOrderStep2, profile: object) -> bool:
            nonlocal invocation_count
            invocation_count += 1
            return original_get_profile(step2_self, profile)  # type: ignore[arg-type]

        failures: list[tuple[int, Result]] = []
        with patch.object(
            step2_module.PositionThirdOrderStep2, "get_profile", counting_get_profile
        ):
            for index, case in enumerate(cases):
                inp = InputParameter.from_dict(case)
                otg = Otg(0.01, dofs=inp.degrees_of_freedom)
                output = OutputParameter(dofs=inp.degrees_of_freedom)
                result = otg.calculate(inp, output)
                if result < 0:
                    failures.append((index, result))

        self.assertEqual(
            failures,
            [],
            f"{len(failures)}/{len(cases)} multi-DOF corpus cases returned an error Result",
        )
        # The acceptance signal for the whole chunk (design constraint 1:
        # measure, don't assume). Observed count at authoring time: 900
        # invocations across 450 cases -- see the chunk's Resolution notes.
        self.assertGreater(
            invocation_count,
            0,
            "PositionThirdOrderStep2.get_profile was never invoked by the multi-DOF corpus",
        )


class TestPhaseSynchronizationCollinear(unittest.TestCase):
    """Post-audit E-5: ``Synchronization.PHASE`` driven through
    ``calculate()`` for a genuinely collinear 2-DOF rest-to-rest move
    (proportional position deltas, zero velocity/acceleration everywhere,
    which is trivially collinear per ``_is_input_collinear``'s algebra).
    Phase sync must succeed without a Step2 solve: both DOFs finish at the
    same duration by scaling the limiting DOF's own timing, not by an
    independent per-DOF time-synchronization solve."""

    def test_collinear_phase_sync_succeeds_without_step2(self) -> None:
        dofs = 2
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0, 5.0])
        inp.per_dof_synchronization = [Synchronization.PHASE, Synchronization.PHASE]

        trajectory = Trajectory(dofs)
        invocation_count = 0
        original_get_profile = step2_module.PositionThirdOrderStep2.get_profile

        def counting_get_profile(step2_self: PositionThirdOrderStep2, profile: object) -> bool:
            nonlocal invocation_count
            invocation_count += 1
            return original_get_profile(step2_self, profile)  # type: ignore[arg-type]

        with patch.object(
            step2_module.PositionThirdOrderStep2, "get_profile", counting_get_profile
        ):
            result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        self.assertEqual(invocation_count, 0, "collinear phase sync should not need Step2")

        for dof, target in enumerate([10.0, 5.0]):
            profile = trajectory.profiles[0][dof]
            self.assertAlmostEqual(profile.p[-1], target, delta=1e-6, msg=f"dof {dof}")
            self.assertAlmostEqual(
                profile.t_sum[-1], trajectory.duration, delta=1e-9, msg=f"dof {dof}"
            )


class TestPhaseSynchronizationFallsBackToTime(unittest.TestCase):
    """Post-audit E-5: when the ``PHASE``-tagged DOFs are NOT collinear
    (here, a current velocity ratio that doesn't match the position-delta
    ratio), otg.md's "Phase synchronize the DOFs when possible, else fall
    back to TIME" contract requires falling back to per-DOF time
    synchronization -- i.e. ``_is_input_collinear`` must return ``False``
    and the non-limiting DOF must go through Step2."""

    def test_non_collinear_phase_sync_falls_back_to_step2(self) -> None:
        dofs = 2
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0, 5.0])
        inp.current_velocity = [0.5, 0.7]  # not proportional to the 10:5 position ratio
        inp.per_dof_synchronization = [Synchronization.PHASE, Synchronization.PHASE]
        self.assertTrue(inp.validate(check_current_state_within_limits=True))

        trajectory = Trajectory(dofs)
        invocation_count = 0
        original_get_profile = step2_module.PositionThirdOrderStep2.get_profile

        def counting_get_profile(step2_self: PositionThirdOrderStep2, profile: object) -> bool:
            nonlocal invocation_count
            invocation_count += 1
            return original_get_profile(step2_self, profile)  # type: ignore[arg-type]

        with patch.object(
            step2_module.PositionThirdOrderStep2, "get_profile", counting_get_profile
        ):
            result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        self.assertGreater(
            invocation_count, 0, "non-collinear phase sync must fall back to a Step2 solve"
        )

        for dof, target in enumerate([10.0, 5.0]):
            profile = trajectory.profiles[0][dof]
            self.assertAlmostEqual(profile.p[-1], target, delta=1e-6, msg=f"dof {dof}")


class TestDiscreteDuration(unittest.TestCase):
    """Post-audit E-6: ``DurationDiscretization.DISCRETE`` driven through
    ``calculate()`` -- the synchronized duration must be rounded up to the
    next multiple of ``delta_time`` (``calculator_target.py``'s
    ``_synchronize`` discrete-rounding branch), not left at the raw
    (non-multiple) time-optimal value."""

    def test_duration_is_rounded_up_to_a_multiple_of_delta_time(self) -> None:
        dofs = 1
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.3])  # natural optimum 8.15, not a multiple of 0.1
        inp.duration_discretization = DurationDiscretization.DISCRETE

        trajectory = Trajectory(dofs)
        delta_time = 0.1
        result = calc.calculate(inp, trajectory, delta_time=delta_time)

        self.assertEqual(result, Result.WORKING)
        natural_optimum = _rest_to_rest_optimal_duration(10.3)
        self.assertGreaterEqual(trajectory.duration, natural_optimum - 1e-9)
        multiples = trajectory.duration / delta_time
        self.assertAlmostEqual(multiples, round(multiples), delta=1e-6)
        self.assertAlmostEqual(trajectory.profiles[0][0].p[-1], 10.3, delta=1e-6)


class TestMinimumDuration(unittest.TestCase):
    """Post-audit E-6: ``InputParameter.minimum_duration`` driven through
    ``calculate()`` -- a 1-DOF move stretched to twice its natural optimal
    duration must land exactly on ``minimum_duration`` (not the natural
    optimum), via a genuine Step2 solve (the 1-DOF fast path is bypassed
    whenever ``minimum_duration is not None``)."""

    def test_duration_is_stretched_to_minimum_duration_via_step2(self) -> None:
        dofs = 1
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0])
        natural_optimum = _rest_to_rest_optimal_duration(10.0)
        inp.minimum_duration = 2.0 * natural_optimum

        trajectory = Trajectory(dofs)
        invocation_count = 0
        original_get_profile = step2_module.PositionThirdOrderStep2.get_profile

        def counting_get_profile(step2_self: PositionThirdOrderStep2, profile: object) -> bool:
            nonlocal invocation_count
            invocation_count += 1
            return original_get_profile(step2_self, profile)  # type: ignore[arg-type]

        with patch.object(
            step2_module.PositionThirdOrderStep2, "get_profile", counting_get_profile
        ):
            result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        self.assertAlmostEqual(trajectory.duration, inp.minimum_duration, delta=1e-9)
        self.assertGreater(invocation_count, 0, "minimum_duration stretch must go through Step2")
        self.assertAlmostEqual(trajectory.profiles[0][0].p[-1], 10.0, delta=1e-6)
        self.assertAlmostEqual(trajectory.profiles[0][0].v[-1], 0.0, delta=1e-6)
        self.assertAlmostEqual(trajectory.profiles[0][0].a[-1], 0.0, delta=1e-6)


class TestTimeIfNecessarySynchronization(unittest.TestCase):
    """Post-audit E-6: ``Synchronization.TIME_IF_NECESSARY`` driven through
    ``calculate()``, both branches of
    ``calculator_target.py``'s early-exit check:

    - "not necessary" (zero target velocity/acceleration): the DOF keeps
      its own short, unstretched optimal profile and simply holds at the
      target once it finishes early -- it is NOT stretched to match the
      slower ``TIME``-synced DOF's duration.
    - "necessary" (non-zero target velocity): the DOF must be stretched to
      the synchronized duration via Step2, since arriving early and
      holding would not reproduce the required non-zero terminal velocity
      at the right moment.
    """

    def test_zero_target_velocity_keeps_its_own_short_duration(self) -> None:
        dofs = 2
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0, 2.0])  # dof0 slow, dof1 fast
        inp.per_dof_synchronization = [Synchronization.TIME, Synchronization.TIME_IF_NECESSARY]

        trajectory = Trajectory(dofs)
        result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        slow_duration = _rest_to_rest_optimal_duration(10.0)
        fast_duration = _rest_to_rest_optimal_duration(2.0)
        self.assertAlmostEqual(trajectory.duration, slow_duration, delta=1e-9)

        fast_profile = trajectory.profiles[0][1]
        self.assertAlmostEqual(fast_profile.p[-1], 2.0, delta=1e-6)
        self.assertAlmostEqual(
            fast_profile.t_sum[-1],
            fast_duration,
            delta=1e-6,
            msg="a not-necessary TIME_IF_NECESSARY DOF must keep its own optimal duration",
        )

    def test_nonzero_target_velocity_stretches_via_step2(self) -> None:
        dofs = 2
        calc = TargetCalculator(dofs)
        inp = _make_position_input(dofs, [10.0, 2.0])
        inp.target_velocity = [0.0, 0.3]
        inp.per_dof_synchronization = [Synchronization.TIME, Synchronization.TIME_IF_NECESSARY]

        trajectory = Trajectory(dofs)
        invocation_count = 0
        original_get_profile = step2_module.PositionThirdOrderStep2.get_profile

        def counting_get_profile(step2_self: PositionThirdOrderStep2, profile: object) -> bool:
            nonlocal invocation_count
            invocation_count += 1
            return original_get_profile(step2_self, profile)  # type: ignore[arg-type]

        with patch.object(
            step2_module.PositionThirdOrderStep2, "get_profile", counting_get_profile
        ):
            result = calc.calculate(inp, trajectory, delta_time=0.001)

        self.assertEqual(result, Result.WORKING)
        slow_duration = _rest_to_rest_optimal_duration(10.0)
        self.assertGreater(invocation_count, 0, "a necessary TIME_IF_NECESSARY sync needs Step2")

        fast_profile = trajectory.profiles[0][1]
        self.assertAlmostEqual(
            fast_profile.t_sum[-1],
            slow_duration,
            delta=1e-6,
            msg="a necessary TIME_IF_NECESSARY DOF must be stretched to the synced duration",
        )
        self.assertAlmostEqual(fast_profile.p[-1], 2.0, delta=1e-6)
        self.assertAlmostEqual(fast_profile.v[-1], 0.3, delta=1e-6)


class TestVelocityControlInterface(unittest.TestCase):
    """Post-audit E-6: ``ControlInterface.VELOCITY`` driven through
    ``Otg.calculate`` -- previously exercised only by
    ``InputParameter.validate``, never through the actual
    ``set_boundary_for_velocity`` / velocity-brake / velocity-step-solver
    dispatch path in ``calculate()``."""

    def test_velocity_interface_reaches_target_velocity(self) -> None:
        dofs = 1
        inp = InputParameter(dofs)
        inp.control_interface = ControlInterface.VELOCITY
        inp.target_velocity = [3.0]
        inp.max_acceleration = [1.0]
        inp.min_acceleration = [-1.0]
        inp.max_jerk = [1.0]

        otg = Otg(0.01, dofs=dofs)
        output = OutputParameter(dofs=dofs)
        result = otg.calculate(inp, output)

        self.assertEqual(result, Result.WORKING)
        profile = output.trajectory.profiles[0][0]
        self.assertAlmostEqual(profile.v[-1], 3.0, delta=1e-6)
        self.assertAlmostEqual(profile.a[-1], 0.0, delta=1e-6)

        final_p, final_v, final_a = output.trajectory.at_time(output.trajectory.duration)
        self.assertAlmostEqual(final_v[0], 3.0, delta=1e-6)
        self.assertAlmostEqual(final_a[0], 0.0, delta=1e-6)


if __name__ == "__main__":
    unittest.main()
